name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout bhoptimer includes
        uses: actions/checkout@v4
        with:
          repository: shavitush/bhoptimer
          path: bhoptimer

      - name: Set up SourcePawn compiler
        uses: rumblefrog/setup-sp@master
        with:
          version: "1.11.x"

      - name: Compile
        run: |
          mkdir -p plugins
          spcomp -i bhoptimer/addons/sourcemod/scripting/include -o plugins/betterseg.smx addons/sourcemod/scripting/betterseg.sp

      - uses: actions/upload-artifact@v4
        with:
          name: betterseg
          path: plugins/betterseg.smx
